### ISSUE TITLE
Create User Registration Endpoint

### ISSUE THREAD

**Issue by RO-HSA** [Super-Patos-Hackaton/backend#2]
## Description
Implement an endpoint to allow Root Administrators to create new users.

## Motivation
This functionality is fundamental for initializing the platform and defining user roles and permissions. Without user registration, other functionalities cannot be tested or utilized.

## Fields Required:
- Email (open text field)
- Squad (Front-end / Back-end / CyberSecurity / UXUI / Data / Games / Marketing / Mobile / QA)
- Access Level (User (default) / Monitor / Manager / Administrator)
- Role (Director / Leader / PM / PO / Techlead / Member (default))

## Tasks
- [ ] Design the user registration data model
- [ ] Implement the user registration API endpoint
- [ ] Create validation logic for the registration form fields
- [ ] Implement email sending functionality to send registration completion links
- [ ] Write unit tests for the registration endpoint
